### PR TITLE
Cleanup: remove old code from old fta-live-iac repo.

### PR DESCRIPTION
**Pull request by julie-ng**
@wviriya @CalumMcL as mentioned in my comment in #23, in my opinion this project code does not below in this repository for the following reasons:

- this repo is for handouts, "leave behinds" not project code.
- if there were a need for sharing project code, keep in mind best practice rule of thumb for deciding repo scope is - code that changes together, lives together. That does not apply here. This repo should be mostly markdown. For the other DevOps sessions, the demos are in separate repos.
- additionally, we should avoid having 3rd party code distributed in this repo. This PR removes jQuery and Bootstrap distributions.

Assigning you both to the PR since you are the original creator and approvers.

Let me know if there are questions. Thanks!

### CODE REVIEW

**Comment by wviriya** [comment]
@julie-ng, I'm fine with your point on removing application code in src folder. However, I'd like to keep Bicep files and YAML pipelines. These are samples intended to be shared with the customers.

**Comment by julie-ng** [comment]
@wviriya can you go into the branch and restore the specific files you want to keep? Or create a new PR removing just the  web app source files.

Thanks!

**Comment by wviriya** [comment]
>

**Comment by wviriya** [comment]
I'm closing this PR and will open a new PR to remove just the web app source files.

**Comment by wviriya** [comment]
I'm closing this PR and will open a new PR to remove just the web app source files.

**Pull request closed without merging**
