### PR TITLE
2022-02-28-brsteph- Adding a Governance "Why" page

### PR DESCRIPTION
**Pull request by brsteph**
- Created a baseline "why" article to help start off the discussion.

### CODE REVIEW

**Comment by JasonBeck2** [comment]
Hi @joanabmartins , adding you to this PR as we chatted about incorporating updates into the Governance session. Brandon has submitted some changes on this PR and I wanted to loop you in for your feedback around the 'why.md' page.

**Review by joanabmartins — APPROVED** [review]
I'm sorry it took me this long to review. Everything makes sense, thank you for contributing.

**Comment by JasonBeck2** [comment]
Closing this PR and instead using this one to incorporate the changes. #67

**Review by rafaelyMSFT — COMMENTED** [review]
Reviewed on 3/17

**Pull request closed without merging**
