### PR TITLE
Added Azure Cost Governance readme.md

### PR DESCRIPTION
**Pull request by vanessabruwer**

### CODE REVIEW

**Comment by vanessabruwer** [comment]
New Cost Governance session as delivered by Paola

**Comment by julie-ng** [comment]
@vanessabruwer I will ping Paola offline and cc you. It's too close to a PowerPoint, which we do not have clearance to share.

**Comment by vanessabruwer** [comment]
@julie-ng these are the screengrabs from her PPT - I thought it was ok if we put in the images, just not the ppt file?

**Comment by julie-ng** [comment]
> @julie-ng these are the screengrabs from her PPT - I thought it was ok if we put in the images, just not the ppt file?

I thought OK for like 1 screengrab of a diagram, but not multiple slides… Let's double check. Will ping you.

**Comment by CalumMcL** [comment]
merged - thanks!

**Pull request merged**
